# Generated by Django 3.2.7 on 2022-02-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop_budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=25)),
                ('mass', models.FloatField(default=0)),
                ('rate_per_kg', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_budget.crop')),
            ],
        ),
    ]
